const vocabularyData = {
    "Week 1": [
        {english: "ability", thai: "ความสามารถ"},
        {english: "absence", thai: "การขาด การไม่อยู่"},
        {english: "access", thai: "การเข้าถึง"},
        {english: "accommodation", thai: "ที่พักอาศัย"},
        {english: "accomplishment", thai: "การทำให้สำเร็จ การบรรลุเป้าหมาย"},
        {english: "accuracy", thai: "ความถูกต้องแม่นยำ"},
        {english: "achievement", thai: "ความสำเร็จ"},
        {english: "addiction", thai: "อาการเสพติด"},
        {english: "adept", thai: "ผู้เชี่ยวชาญ"},
        {english: "adjustment", thai: "การปรับเปลี่ยน"},
        {english: "advantage", thai: "ประโยชน์ ข้อได้เปรียบ"},
        {english: "advice", thai: "คำแนะนำ"},
        {english: "aid", thai: "การช่วยเหลือ"},
        {english: "allowance", thai: "เงินค่าใช้จ่าย"},
        {english: "alternative", thai: "ทางเลือก"},
        {english: "ambiguity", thai: "ความกำกวม"},
        {english: "ambition", thai: "ความทะเยอทะยาน ความใฝ่ฝัน"},
        {english: "ambivalence", thai: "ความไม่แน่ใจ ความคิดสองจิตสองใจ"},
        {english: "announcement", thai: "การประกาศ"},
        {english: "anticipation", thai: "การความหวัง"},
        {english: "apology", thai: "การขออภัย"},
        {english: "apparel", thai: "เครื่องนุ่งห่ม"},
        {english: "appearance", thai: "รูปร่างหน้าตา"},
        {english: "applicant", thai: "ผู้สมัคร"},
        {english: "appointment", thai: "การนัดหมาย"},
        {english: "approach", thai: "การเข้าถึง การเข้าใกล้"},
        {english: "argument", thai: "การโต้แย้งโต้เถียง"},
        {english: "assembly", thai: "การชุมนุม"},
        {english: "asset", thai: "ทรัพย์สิน"},
        {english: "attempt", thai: "ความพยายาม"},
        {english: "attention", thai: "การเอาใจใส่"},
        {english: "attribute", thai: "คุณสมบัติ"},
        {english: "authority", thai: "อำนาจ"}
    ],
    "Week 2": [
        {english: "badge", thai: "เครื่องหมาย เข็ดกลัด"},
        {english: "bankrupt", thai: "บุคคลล้มละลาย"},
        {english: "bargain", thai: "การต่อรอง"},
        {english: "barrier", thai: "สิ่งกีดขวาง อุปสรรค"},
        {english: "benchmark", thai: "เกณฑ์มาตรฐาน"},
        {english: "bias", thai: "อคติ"},
        {english: "border", thai: "ขอบ เขตแดน"},
        {english: "bother", thai: "การรบกวน"},
        {english: "branch", thai: "กิ่งก้าน สาขา"},
        {english: "breakdown", thai: "ความล้มเหลว"},
        {english: "breakthrough", thai: "การพัฒนา ความก้าวหน้า"},
        {english: "brief", thai: "ข้อสรุป"},
        {english: "budget", thai: "งบประมาณ"},
        {english: "calculator", thai: "เครื่องคิดเลข"},
        {english: "campaign", thai: "การรณรงค์ การหาเสียง"},
        {english: "candidate", thai: "ผู้ท้าชิง ผู้เข้าแข่งขัน"},
        {english: "capability", thai: "ความสามารถ"},
        {english: "capacity", thai: "ความจุ"},
        {english: "career", thai: "อาชีพ"},
        {english: "carrier", thai: "บริษัทขนส่ง คนส่งของ"},
        {english: "category", thai: "ประเภท ชนิด"},
        {english: "caution", thai: "การเตือน"},
        {english: "century", thai: "ศตวรรษ"},
        {english: "challenge", thai: "การท้าทาย"},
        {english: "characteristic", thai: "ลักษณะเฉพาะ"},
        {english: "charge", thai: "ค่าธรรมเนียม"},
        {english: "chore", thai: "งานบ้าน"},
        {english: "circumstance", thai: "เหตุการณ์ สภาพ"},
        {english: "client", thai: "ลูกค้า"},
        {english: "cognition", thai: "การรับรู้"},
        {english: "coincidence", thai: "ความบังเอิญ การเกิดขึ้นพร้อมกัน"},
        {english: "collaboration", thai: "การร่วมมือกัน"},
        {english: "colleague", thai: "เพื่อนร่วมงาน"}
    ],
    "Week 3": [
        {english: "command", thai: "คำสั่ง"},
        {english: "commission", thai: "ค่านายหน้า"},
        {english: "compensation", thai: "การชดเชย"},
        {english: "competition", thai: "การแข่งขัน"},
        {english: "component", thai: "ส่วนประกอบ"},
        {english: "compromise", thai: "การตกลงกันได้ การประนีประนอม"},
        {english: "conference", thai: "การประชุม"},
        {english: "confidence", thai: "ความมั่นใจ"},
        {english: "consciousness", thai: "ความมีสติ"},
        {english: "conservative", thai: "นักอนุรักษนิยม"},
        {english: "consideration", thai: "การพิจารณา การไตร่ตรอง"},
        {english: "consistency", thai: "ความสอดคล้อง ความเหนียวแน่น"},
        {english: "consumption", thai: "การบริโภค"},
        {english: "conviction", thai: "การพิพากษาโทษว่าผิด"},
        {english: "contract", thai: "สัญญา"},
        {english: "cooperation", thai: "การร่วมมือ การทำงานร่วมกัน"},
        {english: "correlation", thai: "ความสัมพันธ์กัน"},
        {english: "council", thai: "สภา คณะกรรมการ"},
        {english: "courtesy", thai: "ความสุภาพ"},
        {english: "credit", thai: "ความน่าเชื่อถือ"},
        {english: "criterion", thai: "เกณฑ์ บรรทัดฐาน"},
        {english: "crowd", thai: "ฝูงชน"},
        {english: "cure", thai: "การรักษา"},
        {english: "currency", thai: "ค่าเงิน เงินตรา"},
        {english: "custom", thai: "ประเพณี"}
    ],
    "Week 4": [
        {english: "debris", thai: "ซากปรักหักพัง"},
        {english: "debt", thai: "หนี้"},
        {english: "declaration", thai: "การประกาศ"},
        {english: "decline", thai: "ภาวะตกต่ำ"},
        {english: "dedication", thai: "การอุทิศตน"},
        {english: "demonstration", thai: "การพิสูจน์ การสาธิต การอธิบาย"},
        {english: "density", thai: "ความหนาแน่น"},
        {english: "departure", thai: "การจากไป การออกจาก การออกเดินทาง"},
        {english: "deposit", thai: "เงินฝาก เงินมัดจำ"},
        {english: "destination", thai: "จุดหมาย ปลายทาง"},
        {english: "dictate", thai: "คำสั่ง"},
        {english: "diet", thai: "อาหาร"},
        {english: "dignity", thai: "ความมีเกียรติ ความสง่างาม"},
        {english: "discipline", thai: "การฝึกฝน ระเบียบวินัย"},
        {english: "discount", thai: "ส่วนลด"},
        {english: "discouragement", thai: "การทำให้หมดกำลังใจ"},
        {english: "display", thai: "การแสดง"},
        {english: "disposal", thai: "การจัดการ"},
        {english: "dispute", thai: "การโต้แย้งโต้เถียง"},
        {english: "donation", thai: "การบริจาค"},
        {english: "doubt", thai: "ความสงสัย"},
        {english: "downtown", thai: "ตัวเมือง ใจกลางเมือง"},
        {english: "draft", thai: "ฉบับร่าง"},
        {english: "drill", thai: "การฝึกฝน"},
        {english: "duration", thai: "ความทนทาน"}
    ],
    "Week 5": [
        {english: "earnings", thai: "รายได้"},
        {english: "edge", thai: "ขอบ"},
        {english: "effect", thai: "ผลกระทบ"},
        {english: "effort", thai: "ความพยายาม"},
        {english: "elaboration", thai: "การกระทำอย่างละเอียดประณีต"},
        {english: "election", thai: "การเลือกตั้ง"},
        {english: "empathy", thai: "ความสามารถในการเข้าใจความรู้สึกผู้อื่น"},
        {english: "emphasis", thai: "การเน้น"},
        {english: "enclosure", thai: "การปิด การล้อมรอบ"},
        {english: "encounter", thai: "การพบเจอโดยบังเอิญ"},
        {english: "engagement", thai: "การหมั้น"},
        {english: "enthusiasm", thai: "ความกระตือรือร้น"},
        {english: "equality", thai: "ความเสมอภาค"},
        {english: "essence", thai: "ส่วนประกอบสำคัญ"},
        {english: "estate", thai: "อสังหาริมทรัพย์"},
        {english: "esteem", thai: "ความเคารพนับถือ"},
        {english: "estimate", thai: "การตีราคา"},
        {english: "evidence", thai: "หลักฐาน"},
        {english: "executive", thai: "ผู้บริหาร"},
        {english: "exhibition", thai: "นิทรรศการ"},
        {english: "existence", thai: "การคงอยู่ การดำรงอยู่"},
        {english: "expansion", thai: "การขยายออก"},
        {english: "expectancy", thai: "ความคาดหมาย"},
        {english: "expenditure", thai: "การใช้จ่าย (เงิน)"},
        {english: "expense", thai: "ค่าใช้จ่าย"},
        {english: "experiment", thai: "การทดลอง"},
        {english: "expertise", thai: "ความชำนาญ"},
        {english: "expiration", thai: "การสิ้นสุด การหมดอายุ"},
        {english: "exposure", thai: "การเปิดเผย"},
        {english: "extract", thai: "สารสกัด"}
    ],
    "Week 6": [
        {english: "fabric", thai: "สิ่งทอ"},
        {english: "facilitator", thai: "ผู้ให้บริการ ผู้ช่วยให้เกิดความสะดวก"},
        {english: "facility", thai: "สิ่งอำนวยความสะดวก"},
        {english: "factor", thai: "ปัจจัย"},
        {english: "failure", thai: "ความล้มเหลว"},
        {english: "faith", thai: "ศรัทธา"},
        {english: "fare", thai: "ค่าโดยสาร"},
        {english: "feature", thai: "ลักษณะเฉพาะ"},
        {english: "fellow", thai: "มิตรสหาย"},
        {english: "fence", thai: "รั้ว"},
        {english: "finance", thai: "การเงิน"},
        {english: "fine", thai: "ค่าปรับ"},
        {english: "flaw", thai: "รอยตำหนิ"},
        {english: "flexibility", thai: "ความยืดหยุ่น"},
        {english: "flight", thai: "เที่ยวบิน"},
        {english: "fluency", thai: "ความคล่องแคล่ว"},
        {english: "forecast", thai: "การทำนาย"},
        {english: "fortune", thai: "โชคชะตา"},
        {english: "foundation", thai: "รากฐาน"},
        {english: "founder", thai: "ผู้ก่อตั้ง"},
        {english: "fraction", thai: "เศษส่วน"},
        {english: "franchise", thai: "ใบอนุญาตแฟรนไชส์"},
        {english: "fraud", thai: "การโกง"},
        {english: "frequency", thai: "ความถี่"},
        {english: "fund", thai: "เงินทุน"}
    ],
    "Week 7": [
        {english: "garbage", thai: "ขยะ"},
        {english: "garment", thai: "เสื้อผ้า"},
        {english: "gauge", thai: "เครื่องวัด"},
        {english: "goods", thai: "สินค้า"},
        {english: "graduate", thai: "บัณฑิต"},
        {english: "grasp", thai: "การจับ"},
        {english: "gratitude", thai: "ความกตัญญู"},
        {english: "grocery", thai: "ร้านขายของชำ"},
        {english: "guilt", thai: "ความรู้สึกผิด"},
        {english: "halt", thai: "การหยุกชะงัก การหยุดชั่วคราว"},
        {english: "harmony", thai: "ความสอดคล้อง ความสามัคคี"},
        {english: "hazard", thai: "อันตราย"},
        {english: "haze", thai: "หมอก"},
        {english: "hesitation", thai: "ความลังเลใจ"},
        {english: "honesty", thai: "ความซื่อสัตย์"},
        {english: "humidity", thai: "ความชื้น"},
        {english: "ideal", thai: "อุดมคติ"},
        {english: "ignorance", thai: "ความไม่รู้ ความเขลา"},
        {english: "illustration", thai: "ภาพประกอบ"},
        {english: "imagination", thai: "จินตนาการ"},
        {english: "impression", thai: "ความประทับใจ"},
        {english: "incentive", thai: "สิ่งกระตุ้น"},
        {english: "income", thai: "รายได้"},
        {english: "independent", thai: "คนที่พึ่งพาตนเองได้"},
        {english: "infant", thai: "ทารก"},
        {english: "influence", thai: "อิทธิพล"},
        {english: "inhabitant", thai: "ผู้อยู่อาศัย"},
        {english: "initiative", thai: "การริเริ่ม"},
        {english: "injury", thai: "แผล"},
        {english: "inspector", thai: "ผู้ตรวจสอบ"},
        {english: "inspiration", thai: "แรงบันดาลใจ"},
        {english: "instance", thai: "ตัวอย่าง"},
        {english: "institute", thai: "สถาบัน"}
    ],
    "Week 8": [
        {english: "instructor", thai: "ผู้สอน"},
        {english: "instrument", thai: "อุปกรณ์"},
        {english: "insult", thai: "การดูถูก"},
        {english: "insurance", thai: "การประกัน"},
        {english: "integrity", thai: "ความซื่อสัตย์"},
        {english: "intelligence", thai: "ความฉลาด"},
        {english: "intensity", thai: "ความรุนแรง"},
        {english: "interpreter", thai: "ล่าม"},
        {english: "investment", thai: "การลงทุน"},
        {english: "invitation", thai: "การเชื้อเชิญ"},
        {english: "involvement", thai: "การเข้าร่วม"},
        {english: "irritation", thai: "การทำให้ระคายเคือง"},
        {english: "issue", thai: "ประเด็น หัวข้อ"},
        {english: "itinerary", thai: "แผนการเดินทาง"},
        {english: "jeopardy", thai: "อันตราย"},
        {english: "journal", thai: "วารสาร"},
        {english: "journey", thai: "การเดินทาง"},
        {english: "kind", thai: "ประเภท ชนิด"},
        {english: "kit", thai: "ชุดเครื่องมือ"},
        {english: "labor", thai: "แรงงาน"},
        {english: "lack", thai: "การขาดแคลน"},
        {english: "launch", thai: "การปล่อย"},
        {english: "lawsuit", thai: "คดีความ"},
        {english: "layout", thai: "โครงงาน แผนงาน"},
        {english: "leaflet", thai: "ใบปลิว"},
        {english: "lease", thai: "สัญญาเช่า"},
        {english: "legacy", thai: "มรดก"},
        {english: "leisure", thai: "เวลาว่าง"},
        {english: "liability", thai: "หนี้สิน"},
        {english: "liberal", thai: "นักเสรีนิยม ผู้มีใจกว้าง"},
        {english: "likelihood", thai: "ความเป็นไปได้"},
        {english: "loan", thai: "เงินกู้"},
        {english: "loyalty", thai: "ความซื่อสัตย์"}
    ],
    "Week 9": [
        {english: "maintenance", thai: "การบำรุงรักษา"},
        {english: "majority", thai: "คนส่วนใหญ่"},
        {english: "mandate", thai: "คำสั่ง"},
        {english: "manufacture", thai: "การผลิตด้วยเครื่องจักร"},
        {english: "mean", thai: "ค่าเฉลี่ย"},
        {english: "measurement", thai: "การวัด"},
        {english: "merchandise", thai: "สินค้า"},
        {english: "might", thai: "อำนาจ"},
        {english: "minority", thai: "ชนกลุ่มน้อย"},
        {english: "mistreatment", thai: "การทารุณ"},
        {english: "moral", thai: "คติธรรม"},
        {english: "mortgage", thai: "การจำนอง"},
        {english: "necessary", thai: "ปัจจัยในการดำรงชีวิต สิ่งจำเป็น"},
        {english: "neglect", thai: "การละเลย"},
        {english: "objective", thai: "วัตถุประสงค์"},
        {english: "obligation", thai: "สัญญาผูกมัด"},
        {english: "occasion", thai: "โอกาส"},
        {english: "occupancy", thai: "การครอบครอง"},
        {english: "offence", thai: "การทำผิดกฏหมาย"},
        {english: "offer", thai: "การเสนอ"},
        {english: "official", thai: "พนักงาน ข้าราชการ"},
        {english: "operation", thai: "การผ่าตัด"},
        {english: "origin", thai: "แหล่งกำเนิด"},
        {english: "output", thai: "ผลิตผล"},
        {english: "overheads", thai: "ค่าใช้จ่ายทางธุรกิจ"}
    ],
    "Week 10": [
        {english: "particulars", thai: "รายละเอียด"},
        {english: "patience", thai: "ความอดทน"},
        {english: "peace", thai: "ความสงบสุข"},
        {english: "penalty", thai: "การลงโทษ"},
        {english: "permit", thai: "ใบอนุญาต"},
        {english: "persistence", thai: "การยืนกราน"},
        {english: "persuasion", thai: "การชักชวน"},
        {english: "pleasure", thai: "ความพอใจ"},
        {english: "policy", thai: "นโยบาย"},
        {english: "pollution", thai: "ภาวะมลพิษ"},
        {english: "population", thai: "ประชากร"},
        {english: "possession", thai: "ความเป็นเจ้าของ"},
        {english: "possibility", thai: "ความเป็นไปได้"},
        {english: "posture", thai: "ท่าทาง"},
        {english: "preference", thai: "การชอบมากกว่า"},
        {english: "prejudice", thai: "อคติ"},
        {english: "prescription", thai: "ใบสั่งยา"},
        {english: "pressure", thai: "ความกดดัน"},
        {english: "pretense", thai: "การแสร้งทำ"},
        {english: "prevention", thai: "การป้องกัน"},
        {english: "principle", thai: "หลักการ"},
        {english: "priority", thai: "สิ่งที่สำคัญที่สุด สิ่งที่สำคัญกว่า"},
        {english: "privacy", thai: "ความสันโดษ ความเป็นส่วนตัว"},
        {english: "privilege", thai: "สิทธิพิเศษ"},
        {english: "procedure", thai: "วิธีการ"},
        {english: "profession", thai: "วิชาชีพ"},
        {english: "proficiency", thai: "ความเชี่ยวชาญ ความสามารถ"},
        {english: "profit", thai: "กำไร"},
        {english: "property", thai: "ทรัพย์สิน"},
        {english: "pursuit", thai: "การไล่ตาม"},
        {english: "qualification", thai: "คุณสมบัติ"},
        {english: "queue", thai: "คิว"},
        {english: "quotation", thai: "คำอ้างอิง"}
    ],
    "Week 11": [
        {english: "rear", thai: "ส่วนหลัง ด้านหลัง"},
        {english: "rebound", thai: "การสะท้อนกลับ"},
        {english: "receipt", thai: "ใบเสร็จ"},
        {english: "recession", thai: "การถดถอย"},
        {english: "recognition", thai: "การยอมรับ"},
        {english: "recommendation", thai: "การแนะนำ"},
        {english: "recruit", thai: "สมาชิกใหม่"},
        {english: "relation", thai: "ความสัมพันธ์"},
        {english: "relief", thai: "ความผ่อนคลาย"},
        {english: "removal", thai: "การเอาออก การถอนออก"},
        {english: "renovation", thai: "การบูรณะ การปฏิสังขรณ์"},
        {english: "reference", thai: "การอ้างอิง"},
        {english: "refusal", thai: "การปฏิเสธ"},
        {english: "regulations", thai: "กฎข้อบังคับ"},
        {english: "rehearsal", thai: "การฝึกซ้อม"},
        {english: "reinforcement", thai: "การเสริมแรง"},
        {english: "replacement", thai: "การแทนที่"},
        {english: "representative", thai: "ตัวแทน"},
        {english: "reputation", thai: "ชื่อเสียง"},
        {english: "requirement", thai: "สิ่งที่ต้องการ"},
        {english: "rescue", thai: "การช่วยเหลือ"},
        {english: "reservation", thai: "การจอง"},
        {english: "residence", thai: "ที่อยู่อาศัย"},
        {english: "resistance", thai: "การต่อต้าน"},
        {english: "resource", thai: "แหล่งที่มา"},
        {english: "response", thai: "การตอบสนอง"},
        {english: "restriction", thai: "การจำกัด"},
        {english: "retirement", thai: "การปลดเกษียณ"},
        {english: "revenue", thai: "รายได้"},
        {english: "reverse", thai: "ด้านตรงกันข้าม"},
        {english: "rival", thai: "คู่แข่งขัน ศัตรู"},
        {english: "rivalry", thai: "การแข่งขัน"},
        {english: "routine", thai: "กิจวัตรประจำวัน"}
    ],
    "Week 12": [
        {english: "salary", thai: "เงินเดือน"},
        {english: "salvage", thai: "การกู้ภัย"},
        {english: "satisfaction", thai: "ความพึงพอใจ"},
        {english: "scenery", thai: "วิวทิวทัศน์"},
        {english: "scratch", thai: "รอยข่วน"},
        {english: "section", thai: "ส่วน"},
        {english: "senior", thai: "ผู้อาวุโส"},
        {english: "sequence", thai: "ความต่อเนื่อง"},
        {english: "session", thai: "เวลาในการประชุม"},
        {english: "setback", thai: "การหยุดยั้งความก้าวหน้า"},
        {english: "shortage", thai: "ความขาดแคลน"},
        {english: "significance", thai: "ความสำคัญ"},
        {english: "simulation", thai: "การลอกเลียนแบบ"},
        {english: "solace", thai: "การปลอบใจ สิ่งปลอบใจ"},
        {english: "sort", thai: "ชนิด"},
        {english: "specification", thai: "รายละเอียดเฉพาะ"},
        {english: "spread", thai: "การแพร่กระจาย"},
        {english: "standard", thai: "มาตรฐาน"},
        {english: "stationery", thai: "เครื่องเขียน"},
        {english: "status", thai: "สถานภาพ"},
        {english: "straight", thai: "เส้นตรง"},
        {english: "strategy", thai: "ยุทธศาสตร์ กลวิธี"},
        {english: "strength", thai: "กำลัง"},
        {english: "stress", thai: "ความเครียด"},
        {english: "structure", thai: "โครงสร้าง"},
        {english: "subscription", thai: "เงินบริจาค การบอกรับเป็นสมาชิก"},
        {english: "substitute", thai: "ตัวแทน"},
        {english: "success", thai: "ความสำเร็จ"},
        {english: "suggestion", thai: "ข้อเสนอแนะ"},
        {english: "supervisor", thai: "ผู้บังคับบัญชา"},
        {english: "supplement", thai: "ส่วนเสริม"},
        {english: "supply", thai: "การจัดหาให้"},
        {english: "surface", thai: "พื้นผิว"}
    ],
    "Week 13": [
        {english: "surplus", thai: "ส่วนเกิน"},
        {english: "sympathy", thai: "ความเห็นอกเห็นใจ"},
        {english: "synthesis", thai: "การสังเคราะห์"},
        {english: "tailor", thai: "ช่างตัดเสื้อ"},
        {english: "takeover", thai: "การยึดครอง"},
        {english: "technique", thai: "กลวิธี"},
        {english: "tension", thai: "ความตึงเครียด"},
        {english: "territory", thai: "อาณาเขต"},
        {english: "threat", thai: "คำขู่ การขู่คุกคาม"},
        {english: "token", thai: "เครื่องหมาย"},
        {english: "tool", thai: "เครื่องมือ"},
        {english: "track", thai: "เส้นทาง"},
        {english: "tradition", thai: "ขนบธรรมเนียม ประเพณี"},
        {english: "traffic", thai: "การจราจร"},
        {english: "trail", thai: "รอยเท้า"},
        {english: "treatment", thai: "การรักษา"},
        {english: "trespasser", thai: "ผู้บุกรุก"},
        {english: "uncertainty", thai: "ความไม่แน่นอน"},
        {english: "union", thai: "การรวมกัน"},
        {english: "vacancy", thai: "ตำแหน่งงานว่าง"},
        {english: "valuables", thai: "ของมีค่า"},
        {english: "variation", thai: "การเปลี่ยนแปลง"},
        {english: "variety", thai: "ความหลากหลาย"},
        {english: "vehicle", thai: "ยานพาหนะ"},
        {english: "vendor", thai: "ผู้ขาย"},
        {english: "victim", thai: "ผู้เคราะห์ร้าย"},
        {english: "violation", thai: "การฝ่าฝืน"},
        {english: "visibility", thai: "ทัศนวิสัย"},
        {english: "volunteer", thai: "อาสาสมัคร"},
        {english: "voyage", thai: "การเดินทาง"}
    ],
    "Week 14": [
        {english: "waiter", thai: "บริกรชาย"},
        {english: "wallet", thai: "กระเป๋าสตางค์"},
        {english: "warehouse", thai: "โกดัง"},
        {english: "weakness", thai: "ความอ่อนแอ"},
        {english: "wealth", thai: "ทรัพย์สมบัติ"},
        {english: "weight", thai: "น้ำหนัก"},
        {english: "width", thai: "ความกว้าง"},
        {english: "will", thai: "พินัยกรรม"},
        {english: "willingness", thai: "ความเต็มใจ"},
        {english: "witness", thai: "พยาน"},
        {english: "yield", thai: "ผลผลิต"}
    ]
}; 